### ISSUE TITLE
Bower install doesn't actually work

### ISSUE THREAD

**Issue by rsinger** [talis/bootstrap-sass#32]
You can install via Bower, but the branding, colors, etc. don't actually work.  It just looks like generic bootstrap.

**Comment by danielmatthew** [comment]
You probably want to compile the SCSS.

I did think there was a compiled version included...

**Comment by rsinger** [comment]
That's *after* compiling the SCSS.

**Comment by danielmatthew** [comment]
I think this is resolved now…
