### ISSUE TITLE
Talis Bootstrap SaaS Dropdown Menus in a Table Do Not Overflow causing a Scroll bar

### ISSUE THREAD

**Issue by pads** [talis/bootstrap-sass#35]
In atlas we have many tables which contain an action menu. This menu is a dropdown menu.

If the dropdown menu is selected on the last row in the table, a scroll bar appears instead of the
menu overflowing onto the page footer.

This doesn't happen if there is something with any height in between the table and the footer. In
most cases in Atlas, we have had pagination controls in between the table and the footer, and this
has masked the problem. However, without pagination controls, we have had to insert an empty
paragraph to work around this problem.

<TODO: ML: Screenshots and examples to come>

**Comment by danielmatthew** [comment]
Where does the scrollbar appear: the browser window or the table?

**Comment by pads** [comment]
It's in the table. I believe this only applies to responsive tables, it's something to do with scroll overflow in the CSS I imagine.

**Comment by pads** [comment]
I took the pagination out of this table. It is a responsive table, the only thing below it is a footer.

![clipping](https://cloud.githubusercontent.com/assets/557957/22200077/82777378-e155-11e6-8aef-e3df98924b42.png)

**Comment by danielmatthew** [comment]
[Weird.](https://github.com/talis/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_tables.scss#L174) I'll have a play.

**Comment by danielmatthew** [comment]
So my feeling on this is as follows: I'd rather investigate customising responsive tables in another way - perhaps updating their display property to flex and stacking the rows vertically.
