### ISSUE TITLE
Add missing styles for close button

### ISSUE THREAD

**Issue by pads** [talis/bootstrap-sass#42]
It's available upstream but missing from this fork for some reason.  It currently [lives in Atlas](https://github.com/talis/atlas-app/blob/54aad59eeea248eb88a164a6e7ad63094df4871a/app/assets/stylesheets/close.scss) but should come from here.

**Comment by danielmatthew** [comment]
Interesting. Maybe an include I forgot about?

**Comment by pads** [comment]
I'm happy to patch this if that's all it is.
