### ISSUE TITLE
text-danger is no longer red (it's black)

### ISSUE THREAD

**Issue by junglebarry** [talis/bootstrap-sass#53]
This line sets a danger colour to black:

https://github.com/talis/bootstrap-sass/blob/8dac36967215f61e77e494b2fd532b15b6a3d29a/assets/stylesheets/bootstrap/_variables.scss#L545

but this is then picked up by `text-danger`, here:

https://github.com/talis/bootstrap-sass/blob/8dac36967215f61e77e494b2fd532b15b6a3d29a/assets/stylesheets/bootstrap/_type.scss#L191

This line means that `text-danger` becomes black.  That's a utility class solely for making text red (or danger coloured).  Is this an over-applied cascade?  It doesn't seem like we ought to be doing this - apps now need to override it to get red-coloured text again.

**Comment by danielmatthew** [comment]
Resolved by #59
