### ISSUE TITLE
Navbar hover states are fixed colours; can we transparentize them?

### ISSUE THREAD

**Issue by junglebarry** [talis/bootstrap-sass#54]
When I used the default styling in Shipshape, I got a fixed background-colour for the navbar active/hover states.  I had to retain this piece of customisation in Shipshape:

```scss
$navbar-default-link-hover-bg:             transparentize($black, 0.9) !default;
$navbar-default-link-active-bg:            transparentize($black, 0.9) !default;
```

Could this become part of the design language, so we don't need to customise?

**Comment by danielmatthew** [comment]
Fixed in d7dafde
