### ISSUE TITLE
Allow use of semantic markup for single-page apps

### ISSUE THREAD

**Issue by junglebarry** [talis/bootstrap-sass#55]
Bootstrap 3 has quite strict rules on the elements that can be used in certain places, and this prevents the use of semantic markup.  It'd be good if we could give semantic markup parity, so that we can freely use it.

Examples:

- [ ] Dropdowns are `ul - li - a`, but we ought to use `ul - li - button` for SPA/keyboard interactivity

**Comment by junglebarry** [comment]
The problems with *not* supporting semantic markup:

* We have to manually remember (during implementation and code review) to specify all the accessibility workarounds for non-semantic elements.

* ... that increases the time and cost of delivery, and means it is possible to just forget and introduce bugs, which... increases the time and cost of delivery...

* We have to duplicate event bindings from `click` to explicit keylisteners (`keyup.enter` and `keyup.space` in Angular), and this adds all of the duplication issues above **and** has a performance cost.  When we do this for thousands of items on a page, our app gets slower.

* The codebase is much larger, thanks to all the extra manually-specified event bindings and accessibility workarounds.

* larger bundles take longer to download, leading to a worse user experience.

* larger bundles cost us more in network transfer fees.

I could go on all day :)

**Comment by danielmatthew** [comment]
@junglebarry Long overdue, but this is now catered for.
